<table border="0" cellspacing="0" cellpadding="3" width="100%" bgcolor="#FFFFFF">
   <tr>
    <td><a href="../reservation/day.php"><img src="includes/logo-left.jpg" border="0"/></a></td>
    <td align="center"><img src="includes/logo-center.jpg" /></td>
    <td><img src="includes/logo-right.jpg" /></td></tr>
</table>
       
<table width="100%" cellpadding="3" cellspacing="0">
	<tr bgcolor="#5E86B9">
          
	  <td align="center" class="td2"><a href="index.php" class="link2">View/create person</a></td>
	  <td align="center" class="td2"><a href="band.php" class="link2">View/create band</a></td>
	  <td align="center" class="td2"><a href="payment.php" class="link2">View equipment</a></td>
	  <td align="center" class="td2"><a href="payment.php" class="link2">Inspect equipment</a></td>
      <td align="center" class="td2"><a href="admin.php" class="link2">Help</a></td>
	  <td align="center" class="td2"><a href="help.php" class="link2">Administrator</a></td>
      
	</tr>
</table>