<table border="0" algin="center" valign="top" width="100%">
  <tr>
    <td align="center" valign="top" nowrap>
      <table class="formTable" align="center" valign="top" cellpadding="3" cellspacing="0">
        <tr>
          <td class="listHeader" align="right" valign="middle" nowrap>
            &nbsp;
                 <a class="help" href="" onClick="window.open('/speednet/sphelp/All_Default.htm#','GeneratedSpeedPortalWindow','menubar=no,width=550,height=400,resizable,toolbar=no,location=no,directories=no,scrollbars');return false;"> Help
          </td>
        </tr>
        <tr>
          <td class="bodyColor" align="center" valign="middle" nowrap>
            <table border="0" align="center" valign="middle">
              <tr>
                <td align="center" valign="middle" nowrap>
     		  <font class="warningText"><font style="font-size: 11pt;">
                  <b>&nbsp;&nbsp;&nbsp;&nbsp;No Data Found&nbsp;&nbsp&nbsp;&nbsp;</b><br>
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr class="actionRow">
          <td align="center" valign="middle">
	  <button onclick="backBtnClick();" class="formButton"><font class="buttonText">&nbsp;&nbsp;&nbsp;&nbsp; Back &nbsp;&nbsp;&nbsp;&nbsp;</button>
            &nbsp;
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
