<?
//  Common Style Settings
?>
<style type="text/css">
.title{color:#ffffff;font-family:arial, helvetica, sansserif;font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none}
.titleBlack{color:#000000;font-family:arial, helvetica, sansserif;font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none}
.pageTitle{color:#000000;font-family:arial, helvetica, sansserif;font-size:16pt;font-weight:bold;font-style:normal;text-decoration:none}
.pageTitleInv{color:#880033;font-family:arial, helvetica, sansserif;font-size:16pt;font-weight:bold;font-style:normal;text-decoration:none}
.headline{color:#000000;font-family:arial, helvetica, sansserif;font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none}
.headlineWhite{color:#ffffff;font-family:arial, helvetica, sansserif;font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none}
.subHeadline{color:#000000;font-family:arial, helvetica, sansserif;font-size:10pt;font-weight:normal;font-style:italic;text-decoration:none}
.subHeadlineWhite{color:#ffffff;font-family:arial, helvetica, sansserif;font-size:10pt;font-weight:normal;font-style:italic;text-decoration:none}
.bodytext{color:#000000;font-family:arial, helvetica, sansserif;font-size:10pt;font-weight:normal;font-style:normal;text-decoration:none}
.warningText{color:#ff3300;font-family:arial, helvetica, sansserif;font-size:7pt;font-weight:normal;font-style:normal;text-decoration:none}
.label{color:#000000;font-family:arial, helvetica, sansserif;font-size:10pt;font-weight:bold;font-style:normal;text-decoration:none}
.labelWhite{color:#ffffff;font-family:arial, helvetica, sansserif;font-size:10pt;font-weight:bold;font-style:normal;text-decoration:none}
.data{color:#000000;font-family:arial, helvetica, sansserif;font-size:10pt;font-weight:normal;font-style:normal;text-decoration:none}
.dataItalic{color:#000000;font-family:arial, helvetica, sansserif;font-size:10pt;font-weight:normal;font-style:italic;text-decoration:none}
.notes{color:#000000;font-family:arial, helvetica, sansserif;font-size:8pt;font-weight:normal;font-style:normal;text-decoration:none}
.edit{color:#ffffff;font-family:arial, helvetica, sansserif;font-size:8pt;font-weight:normal;font-style:normal;text-decoration:underline}
.help{color:#ffffff;font-family:arial, helvetica, sansserif;font-size:12pt;font-weight:bold;font-style:normal;text-decoration:underline}
.headerColor {background-color:#5588aa;font-family:arial, helvetica, sansserif;font-size:7pt;font-weight:normal;font-style:normal;text-decoration:none}
.bodyColor {background-color:#99e0ff;font-family:arial, helvetica, sansserif;font-size:7pt;font-weight:normal;font-style:normal;text-decoration:none}
.footer{color:#000000;font-family:arial, helvetica, sansserif;font-size:7pt;font-weight:normal;font-style:normal;text-decoration:none}
.footerLink{color:#0000ff;font-family:arial, helvetica, sansserif;font-size:7pt;font-weight:normal;font-style:normal;text-decoration:underline}
.buttonText{color:#000000;font-family:arial, helvetica, sansserif;font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none}
.fileLink{color:#0000ff;font-family:arial, helvetica, sansserif;font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none}
.pageLink{color:#0000ff;font-family:arial, helvetica, sansserif;font-size:9pt;font-weight:normal;font-style:normal;text-decoration:underline}
.ivanTest{color:#000000;font-family:arial, helvetica, sansserif;font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none}
.menuRadioBtn{vertical-align:text-top;height:24;width:24}
</style>

